import type { Metadata } from 'next'
import { IBM_Plex_Mono} from 'next/font/google'
import './globals.css'

const ibm = IBM_Plex_Mono({ subsets: ['latin'], weight:['100','200','300'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className}>{children}</body>
    </html>
  )
}
